### ISSUE TITLE
JitPack build fails

### ISSUE THREAD

**Issue by mim1q** [Globox1997/RpgDifficulty#51]
[Here's](https://jitpack.io/com/github/globox1997/rpgdifficulty/1.19-d7bbd73316-1/build.log) a link to the log from jitpack.io  
Seems like [the file you referenced](https://github.com/sormuras/bach/raw/master/install-jdk.sh) in `jitpack.yml` doesn't exist anymore, so JitPack tries to use the default Java 8 instead of 17

According to [this article](https://dev.to/cicirello/how-to-configure-jitpack-for-recent-jdk-versions-4pek), the following `jitpack.yml` file should work:

```yml
jdk:
  - openjdk17
before_install:
  - sdk install java 17.0.3-tem
  - sdk use java 17.0.3-tem
```
